# Site settings
baseurl = "http://www.twopennycode.com/"
languageCode = "en-us"
title = "Twopenny code"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = "spf13"

[params]
	name = "Simon Korzunov"
	description = "About prorgamming"
	bio = "Passionate developer - Proud father"
	twitter = "twopSK"
	enableRSS = true

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = "(c) Simon Korzunov, powered by Hugo"
	# Sharing options and author information in posts
	aboutAuthor = "A former game developer, proud father, C# lover, WedDev learner/struggler and a Microsoft employee."
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/twopSK"
    facebook = "https://www.facebook.com/simon.kor.712"
    github   = "https://www.github.com/twop"